# Generated by Django 5.0.3 on 2024-03-30 03:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='property',
            new_name='related_property',
        ),
        migrations.AlterField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
