# Generated by Django 5.0.3 on 2024-03-30 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_rename_related_property_message_property_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_property_message',
            field=models.BooleanField(default=False),
        ),
    ]
