# Generated by Django 5.0.3 on 2024-03-30 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_remove_message_receiver_remove_message_sender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='is_property_message',
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
    ]
