# Generated by Django 5.0.3 on 2024-03-30 23:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_remove_message_is_property_message_message_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_property_message',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.property'),
        ),
        migrations.AlterField(
            model_name='message',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.tenant'),
        ),
    ]
