# Generated by Django 5.0.3 on 2024-03-31 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0010_rename_message_chatmessage_content_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='is_property_message',
            new_name='is_delivered',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='tenant',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='messages/files'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_messages', to='User.property'),
        ),
    ]
