# Generated by Django 5.0.3 on 2024-03-31 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0011_rename_is_property_message_chatmessage_is_delivered_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager_test_chat', to='User.tenant'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenants_manger', to='User.manager'),
        ),
    ]
