# Generated by Django 5.0.3 on 2024-04-01 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0012_manager_tenant_alter_tenant_manager'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='is_delivered',
            new_name='is_received',
        ),
    ]
